# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
#  - name: Demo
#    url: '#about'
#    weight: 10
#  - name: Posts
#    url: '#posts'
#    weight: 20

main:
  - name: Experience
    url: '#experience'
    weight: 1
  - name: Teaching
    url: courses/
    weight: 3
  - name: Publication
    url: '#publications'
    weight: 2
  - name: Contact
    url: '#contact'
    weight: 5
